name: Lint

on:
  # Run on all pushes and on all pull requests.
  push:
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint: #----------------------------------------------------------------------
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Lint against the high/low versions of each PHP major.
        php: ['5.6', '7.0', '7.4', '8.0', '8.1', '8.2']

    name: "Lint: PHP ${{ matrix.php }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=-1, display_errors=On, log_errors_max_len=0
          coverage: none
          tools: cs2pr

      # Install dependencies and handle caching in one go.
      # @link https://github.com/marketplace/actions/install-composer-dependencies
      - name: Install Composer dependencies - normal
        uses: "ramsey/composer-install@v2"

      - name: Lint against parse errors
        if: ${{ matrix.php >= '7.2' }}
        run: composer lint -- --checkstyle | cs2pr

      - name: Lint against parse errors
        if: ${{ matrix.php < '7.2' }}
        run: composer lint -- --exclude build --checkstyle | cs2pr
